version: "3.3"

services:

  zappa:
    tty: true
    build:
      context: .
      dockerfile: zappa.Dockerfile
      args:
        - input_runtime=${input_runtime:-}
    hostname: zappa
    #environment:
    #  - input_aws_access_key_id=${input_aws_access_key_id:?"Missing a required variable `input_aws_access_key_id`"}
    #  - input_aws_secret_access_key=${input_aws_secret_access_key:?"Missing a required variable `input_aws_secret_access_key`"}
    #  - input_aws_default_region=${input_aws_default_region:?"Missing a required variable `input_aws_default_region`"}
    #  - input_project_name=${input_project_name:?"Missing a required variable `input_project_name`"}
    #  - input_stage
    #  # TODO: Pass somehow the rest of the optional settings: `input_django_settings` and `input_runtime`
    volumes:
      - ${input_app_dir}:/var/task

  # This is a service that mimicks how Github runs the container so you
  github:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#docker-container-filesystem
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - .:/opt/action:ro
      - ${input_app_dir:-./test-project}:/github/workspace:ro
    working_dir: /github/workspace


