# A helper for testing
#
version: "3.3"
services:
  zappa:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    hostname: zappa
    environment:
      - input_app_dir=${input_app_dir:?"input_app_dir variable missing. Set to point to the root directory of your Django app."}
      - input_aws_access_key_id=${input_aws_access_key_id:?"Missing a required variable `input_aws_access_key_id`"}
      - input_aws_secret_access_key=${input_aws_secret_access_key:?"Missing a required variable `input_aws_secret_access_key`"}
      - input_aws_default_region=${input_aws_default_region:?"Missing a required variable `input_aws_default_region`"}
      - input_project_name=${input_project_name:?"Missing a required variable `input_project_name`"}
      - input_stage
      # TODO: Pass somehow the rest of the optional settings: `input_django_settings` and `input_runtime`
    volumes:
      - ${input_app_dir}:/var/task

