name: Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run bats tests
        run: |
            #!/bin/bash
            sudo add-apt-repository ppa:duggan/bats
            sudo apt-get update -q
            sudo apt-get install -q bats
            bats --tap bats
